server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/user_db_sync?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

client:
  point-service:
    url: ${CLIENT_POINT_SERVICE_URL:http://localhost:8083}
