server:
  port: 8086

spring:
  application:
    name: pointservice
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/point_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8084}
