services:
  board-db-sync:
    image: mysql:8.0
    container_name: board-db-sync
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: board_db_sync
    ports:
      - "3306:3306"
    volumes:
      - ./board-db/data:/var/lib/mysql
    networks:
      - msa-network

  user-db-sync:
    image: mysql:8.0
    container_name: user-db-sync
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db_sync
    ports:
      - "3307:3306"
    volumes:
      - ./user-db/data:/var/lib/mysql
    networks:
      - msa-network

  point-db-sync:
    image: mysql:8.0
    container_name: point-db-sync
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: point_db_sync
    ports:
      - "3308:3306"
    volumes:
      - ./point-db/data:/var/lib/mysql
    networks:
      - msa-network

  userservice-sync:
    build: ./userservice-sync
    container_name: userservice-sync
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db-sync:3306/user_db_sync?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      CLIENT_POINT_SERVICE_URL: http://pointservice-sync:8083
    depends_on:
      - user-db-sync
    networks:
      - msa-network

  boardservice-sync:
    build: ./boardservice-sync
    container_name: boardservice-sync
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://board-db-sync:3306/board_db_sync?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      USER_SERVICE_URL: http://userservice-sync:8081
      CLIENT_POINT_SERVICE_URL: http://pointservice-sync:8083
    depends_on:
      - board-db-sync
    networks:
      - msa-network

  pointservice-sync:
    build: ./pointservice-sync
    container_name: pointservice-sync
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://point-db-sync:3306/point_db_sync?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      USER_SERVICE_URL: http://userservice-sync:8081
    depends_on:
      - point-db-sync
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
